# Generated by Django 6.0.5 on 2026-05-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Store name (e.g., 'Westlands Branch')", max_length=255, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Geographic latitude', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Geographic longitude', max_digits=9)),
                ('address', models.TextField(help_text='Full physical address of the store')),
                ('phone_number', models.CharField(blank=True, help_text='Store contact number', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this store is currently operational')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Location',
                'verbose_name_plural': 'Store Locations',
                'ordering': ['name'],
            },
        ),
    ]
