# Generated by Django 6.0.5 on 2026-05-20 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_address', models.TextField(help_text='Delivery destination address')),
                ('customer_latitude', models.DecimalField(decimal_places=6, help_text='Customer location latitude', max_digits=9)),
                ('customer_longitude', models.DecimalField(decimal_places=6, help_text='Customer location longitude', max_digits=9)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone number for SMS notification', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance in kilometers from store to customer', max_digits=8)),
                ('fare_ksh', models.PositiveIntegerField(help_text='Delivery fare in Kenyan Shillings (KES)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional delivery notes or special instructions')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliveries', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='stores.store')),
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
