# Generated by Django 6.0.5 on 2026-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.PositiveIntegerField(default=200, help_text='Flat rate for distances up to Base KM (in KES)')),
                ('base_km', models.DecimalField(decimal_places=2, default=10.0, help_text='Kilometers covered by the Base Fare', max_digits=5)),
                ('extra_rate_per_km', models.PositiveIntegerField(default=50, help_text='KES charged per extra kilometer beyond the Base KM')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
    ]
